"""case source

Revision ID: 20ebd955446a
Revises: 700e9301e43a
Create Date: 2026-08-22 23:06:55.057567

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '20ebd955446a'
down_revision: str | None = '700e9301e43a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('source', sa.String(length=16), server_default='razorpay', nullable=False))
    op.create_index(op.f('ix_recovery_cases_source'), 'recovery_cases', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_source'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'source')
    # ### end Alembic commands ###
