"""voice calls

Revision ID: 2ba381731bd6
Revises: 8ab387bf7835
Create Date: 2026-08-22 20:11:19.125708

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '2ba381731bd6'
down_revision: str | None = '8ab387bf7835'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recovery_case_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('room_name', sa.String(length=128), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('dialled_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('detected_intent', sa.String(length=32), nullable=True),
    sa.Column('final_node_id', sa.String(length=64), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_recovery_case_id'), 'voice_calls', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_voice_calls_room_name'), 'voice_calls', ['room_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_calls_room_name'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_recovery_case_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    # ### end Alembic commands ###
