"""payment link on recovery case

Revision ID: 700e9301e43a
Revises: 2ba381731bd6
Create Date: 2026-08-22 22:36:47.594794

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '700e9301e43a'
down_revision: str | None = '2ba381731bd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('payment_link_id', sa.String(length=64), nullable=True))
    op.add_column('recovery_cases', sa.Column('payment_link_url', sa.String(length=255), nullable=True))
    op.add_column('recovery_cases', sa.Column('payment_link_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'payment_link_sent_at')
    op.drop_column('recovery_cases', 'payment_link_url')
    op.drop_column('recovery_cases', 'payment_link_id')
    # ### end Alembic commands ###
