"""initial schema

Revision ID: 8ab387bf7835
Revises: 
Create Date: 2026-08-22 18:31:14.444800

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '8ab387bf7835'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_customer_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('error_reason', sa.String(length=128), nullable=True),
    sa.Column('error_source', sa.String(length=64), nullable=True),
    sa.Column('error_step', sa.String(length=64), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index(op.f('ix_payments_razorpay_customer_id'), 'payments', ['razorpay_customer_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_invoice_id'), 'payments', ['razorpay_invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_subscription_id'), 'payments', ['razorpay_subscription_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=True),
    sa.Column('original_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('halted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_payment_id', sa.String(length=64), nullable=True),
    sa.Column('recovered_amount', sa.Integer(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index(op.f('ix_recovery_cases_razorpay_customer_id'), 'recovery_cases', ['razorpay_customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_razorpay_subscription_id'), 'recovery_cases', ['razorpay_subscription_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=64), nullable=True),
    sa.Column('plan_amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_razorpay_customer_id'), 'subscriptions', ['razorpay_customer_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=128), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id')
    )
    op.create_index('ix_webhook_events_unprocessed', 'webhook_events', ['processed_at'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recovery_case_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_webhook_events_unprocessed', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_subscriptions_razorpay_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_razorpay_subscription_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_razorpay_customer_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payments_razorpay_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('customers')
    # ### end Alembic commands ###
