"""voice call transitions

Revision ID: bf75cb885a95
Revises: 20ebd955446a
Create Date: 2026-08-23 22:51:49.778025

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'bf75cb885a95'
down_revision: str | None = '20ebd955446a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_calls', sa.Column('transitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_calls', 'transitions')
    # ### end Alembic commands ###
